export const HOTELS = [
  {
    id: 1,
    name: "Luxury Oceanfront Resort",
    location: "Maldives",
    price: 450,
    rating: 4.8,
    reviews: 245,
    image: "/images/hotel-oceanfront-maldives.jpg",
    description: "Experience ultimate luxury with breathtaking ocean views and world-class amenities.",
    amenities: ["Pool", "Spa", "Restaurant", "WiFi", "Gym", "Beach Access"],
  },
  {
    id: 2,
    name: "Mountain Retreat Wellness",
    location: "Switzerland",
    price: 380,
    rating: 4.7,
    reviews: 189,
    image: "/images/hotel-mountain-switzerland.jpg",
    description: "Alpine luxury with panoramic mountain views and premium wellness facilities.",
    amenities: ["Spa", "Hiking", "Restaurant", "WiFi", "Gym", "Library"],
  },
  {
    id: 3,
    name: "Urban Elegance Downtown",
    location: "New York",
    price: 320,
    rating: 4.6,
    reviews: 312,
    image: "/images/hotel-urban-newyork.jpg",
    description: "Sophisticated city living in the heart of Manhattan with stunning skyline views.",
    amenities: ["Rooftop Bar", "Gym", "Restaurant", "WiFi", "Business Center", "Concierge"],
  },
  {
    id: 4,
    name: "Tropical Paradise Island",
    location: "Bora Bora",
    price: 520,
    rating: 4.9,
    reviews: 156,
    image: "/images/hotel-tropical-borabora.jpg",
    description: "Overwater bungalows with direct lagoon access in a pristine tropical setting.",
    amenities: ["Beach", "Pool", "Spa", "Watersports", "Restaurant", "WiFi"],
  },
  {
    id: 5,
    name: "Historic Charm European",
    location: "Paris",
    price: 290,
    rating: 4.5,
    reviews: 278,
    image: "/images/hotel-historic-paris.jpg",
    description: "Classic Parisian elegance with ornate architecture and timeless sophistication.",
    amenities: ["Restaurant", "Bar", "WiFi", "Business Center", "Concierge", "Luggage Storage"],
  },
  {
    id: 6,
    name: "Desert Luxury Oasis",
    location: "Dubai",
    price: 400,
    rating: 4.7,
    reviews: 234,
    image: "/images/hotel-desert-dubai.jpg",
    description: "Ultra-modern desert palace with cutting-edge architecture and premium services.",
    amenities: ["Pool", "Spa", "Restaurant", "Gym", "WiFi", "Valet Parking"],
  },
  {
    id: 7,
    name: "Coastal Boutique Getaway",
    location: "Greece",
    price: 270,
    rating: 4.6,
    reviews: 198,
    image: "/images/hotel-coastal-greece.jpg",
    description: "Charming seaside boutique hotel with authentic Mediterranean charm.",
    amenities: ["Beach", "Restaurant", "Bar", "WiFi", "Pool", "Garden"],
  },
  {
    id: 8,
    name: "Forest Eco-Luxury Lodge",
    location: "Costa Rica",
    price: 350,
    rating: 4.8,
    reviews: 167,
    image: "/images/hotel-eco-costarica.jpg",
    description: "Sustainable luxury immersed in pristine rainforest with wildlife experiences.",
    amenities: ["Nature Trails", "Spa", "Restaurant", "WiFi", "Pool", "Eco-Tours"],
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Travel Blogger",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    quote: "StayEase made our honeymoon unforgettable. Exceptional service and stunning properties!",
    rating: 5,
  },
  {
    id: 2,
    name: "Michael Chen",
    role: "Business Executive",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    quote: "Professional, reliable, and always there when we need them. Highly recommended!",
    rating: 5,
  },
  {
    id: 3,
    name: "Emma Rodriguez",
    role: "Family Travel Enthusiast",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    quote: "Family loved every moment. Great accommodations and amazing staff support.",
    rating: 5,
  },
];

export const TEAM_MEMBERS = [
  {
    id: 1,
    name: "Emma Johnson",
    role: "Founder & CEO",
    image: "/images/team-ceo.jpg",
  },
  {
    id: 2,
    name: "James Chen",
    role: "Chief Operations Officer",
    image: "/images/team-coo.jpg",
  },
  {
    id: 3,
    name: "David Martinez",
    role: "Director of Partnerships",
    image: "/images/team-director.jpg",
  },
  {
    id: 4,
    name: "Sophie Williams",
    role: "Customer Experience Lead",
    image: "/images/team-experience.jpg",
  },
];

export const AMENITY_ICONS: Record<string, string> = {
  "Pool": "Waves",
  "Spa": "Dumbbell",
  "Restaurant": "UtensilsCrossed",
  "WiFi": "Wifi",
  "Gym": "Activity",
  "Beach Access": "Anchor",
  "Rooftop Bar": "Wine",
  "Business Center": "Briefcase",
  "Concierge": "Phone",
  "Library": "BookOpen",
  "Hiking": "Mountain",
  "Watersports": "Sailboat",
  "Bar": "Wine",
  "Garden": "Leaf",
  "Nature Trails": "TreePine",
  "Eco-Tours": "Compass",
  "Luggage Storage": "Package",
  "Valet Parking": "Parking",
};
